#cloud-config
write_files:
  - content: |
      [Unit]
      Description=TFE agent
      
      [Service]
      Type=simple
      Environment="TFC_ADDRESS=https://${dns_hostname}.${dns_zonename}"
      Environment="TFC_AGENT_TOKEN=${agent_token}"
      Environment="TFC_AGENT_NAME=INSTANCE_ID_WILL_BE_PLACED_HERE"
      User=root
      WorkingDirectory=/opt/tfe-agent
      ExecStart=/opt/tfe-agent/tfc-agent
      Restart=always
      RestartSec=30
      TimeoutStartSec=30
      TimeoutStopSec=30
      
      [Install]
      WantedBy=multi-user.target
    permissions: '0750'
    path: /etc/systemd/system/tfe-agent.service
runcmd:
  - curl https://releases.hashicorp.com/tfc-agent/1.4.0/tfc-agent_1.4.0_linux_amd64.zip --output /tmp/tfc-agent_1.4.0_linux_amd64.zip 
  - mkdir -p /opt/tfe-agent
  - apt-get update
  - apt-get install unzip
  - unzip /tmp/tfc-agent_1.4.0_linux_amd64.zip  -d /opt/tfe-agent
  - export INSTANCE_ID=`curl http://169.254.169.254/latest/meta-data/instance-id`
  - sed -i "s/INSTANCE_ID_WILL_BE_PLACED_HERE/$INSTANCE_ID/g" /etc/systemd/system/tfe-agent.service
  - systemctl daemon-reload
  - systemctl start tfe-agent
  - systemctl enable tfe-agent.service
packages_update: true  