#cloud-config
write_files:
  - content: |
      [Unit]
      Description=TFE agent
      
      [Service]
      Type=simple
      Environment="TFC_ADDRESS=https://${dns_hostname}.${dns_zonename}.com"
      Environment="TFC_AGENT_TOKEN=${agent_token}"
      Environment="TFC_AGENT_NAME=patrick-agent1"
      User=root
      WorkingDirectory=/opt/tfe-agent
      ExecStart=/opt/tfe-agent/tfc-agent
      Restart=always
      RestartSec=30
      TimeoutStartSec=30
      TimeoutStopSec=30
      
      [Install]
      WantedBy=multi-user.target
    permissions: '0750'
    path: /etc/systemd/system/tfe-agent.service
runcmd:
  - sudo curl https://releases.hashicorp.com/tfc-agent/1.4.0/tfc-agent_1.4.0_linux_amd64.zip --output /tmp/tfc-agent_1.4.0_linux_amd64.zip 
  - sudo mkdir -p /opt/tfe-agent
  - sudo apt-get update
  - sudo apt-get install unzip
  - sudo unzip /tmp/tfc-agent_1.4.0_linux_amd64.zip  -d /opt/tfe-agent
  - sudo systemctl daemon-reload
  - sudo systemctl start tfe-agent.service
  - sudo systemctl enable tfe-agent.service
packages_update: true  